from google.adk.agents.llm_agent import Agent
from google.adk.models.lite_llm import LiteLlm
from google.adk.tools import ToolContext
from google.adk.agents import ParallelAgent,SequentialAgent
from google.adk.agents.callback_context import CallbackContext
from typing import Optional,List
from pydantic import BaseModel,Field
import os
##############################
#      SETUP OPENROUTER      #
##############################

# Get the OpenRouter API key from environment variables
openrouter_api_key = os.environ.get("OPENROUTER_API_KEY")

# Set up the model using LiteLlm with OpenRouter
model = LiteLlm(
    model="openrouter/z-ai/glm-4.5-air:free",
    api_key=openrouter_api_key
)

##############################
#         CALLBACKS          #
##############################

def check_if_agent_completed(callback_context: CallbackContext):
    """
    This function is a callback to check if an agent is completed.

    Args:
        callback_context (CallbackContext): The context of the callback.

    Prints a message with the name of the agent that is completed.
    """
    agent_name = callback_context.agent_name
    print(f"Agent {agent_name} is completed")

def check_if_agent_started(callback_context: CallbackContext):
    """
    This function is a callback to check if an agent is started.

    Args:
        callback_context (CallbackContext): The context of the callback.

    Prints a message with the name of the agent that is started.
    """
    agent_name = callback_context.agent_name
    print(f"Agent {agent_name} is started")

##############################
#         SUBTOPIC AGENT     #
##############################

subtopic = Agent(
    model=model,
    name='subtopic_agent',
    description='A helpful assistant helps to generate subtopics in one word',
    instruction="""
    **Your Core Identity and Sole Purpose:**
        Generate 3 sub topics for the topic given by the user in a specific format.
    
    ** Output Schema**
        1. {topic 1}
        2. {topic 2}
        3. {topic 3}
    """,
    before_agent_callback=check_if_agent_started,
    after_agent_callback=check_if_agent_completed,
)
def text_gen(topic:str,tool_context: ToolContext):
    """
    Generate text for a given topic and add it to the tool context state.

    Args:
        topic (str): The topic to generate text for.
        tool_context (ToolContext): The tool context to add the generated text to.

    Returns:
        str: A message indicating that the subtopic has been added to the state.
    """
    print(f"Generating text for topic: {topic}")
    if tool_context.state.get('subtopic') is None:
        tool_context.state['subtopic'] = [topic]
    else:
        tool_context.state['subtopic'].append(topic)
    
    return f"Subtopic '{topic}' has been added to the state."


##############################
#  PARALLEL RESEARCH AGENT   #
##############################

presearch_agent = ParallelAgent(name='presearch_agent', sub_agents=[
    Agent(
        model=model,
        name=f'research_agent_{i+1}',
        description='A helpful assistant helps to call tool',
        instruction=f"""
        **Your Core Identity and Sole Purpose:**
            Generate relevant research findings for the topic given by the user in a specific format.

        *** Execution Steps ***
            1. Just call tool `text_gen` ONE AND ONLY with the topic number {i+1} from the three topics generated by the subtopic agent.
            2. get the tool result and output that""",
        before_agent_callback=check_if_agent_started,
        after_agent_callback=check_if_agent_completed,
        tools= [text_gen]
    ) for i in range(3)
])


root_agent = Agent(
    model=model,
    name='root_agent',
    description='A helpful assistant to summarize all research findings',
    instruction='First understand the user question, then find relevant research findings using `findings_agent` sub-agents, and finally summarize those findings.',
    sub_agents=[SequentialAgent(name="findings_agent", sub_agents=[subtopic, presearch_agent],description="Executes a sequence of agents")],
    before_agent_callback=check_if_agent_started,
    after_agent_callback=check_if_agent_completed
)

